### ISSUE TITLE
Agree on a line length for our package.

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#102]
[PEP8 convention](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) calls for a line length of ~80 characters:

> Limit all lines to a maximum of 79 characters.
>
> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

However, I like something a bit longer.  Around 120 characters.  I don't mind doing _120_ for both code and docstrings, but I can do _120_ for code and _72_ for docstrings.

Let me know if you prefer something different @sdhutchins.

**Comment by grabear** [comment]
We can add this to the contributing file.
#81

**Comment by sdhutchins** [comment]
I'm a pep8 fan so... :grimacing: :grin:

**Comment by grabear** [comment]
Can you meet me half-way at 100 characters??  :sweat_smile: 

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters), provided that comments and docstrings are still wrapped at 72 characters.

**Comment by sdhutchins** [comment]
How about this...

If you can, < 80, but if not, no greater than 100?

**Comment by Spindel** [comment]
Try adding:
```
[flake8]
max-line-length = 100
```

to your setup.cfg then

**Comment by sdhutchins** [comment]
Thanks for that @Spindel

**Comment by grabear** [comment]
Nice.  Thanks @Spindel for checking out our repository.

**Comment by sdhutchins** [comment]
Addressed with commit 4b7b1d86521e5ef6ec1657bea9aeeddb27016e4e
