### ISSUE TITLE
Make a list of files that are using access tokens or some sort of keys.

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#28]
_From @grabear on April 14, 2017 0:2_

- [x] GitHub with our Applications page
    - R
    - Shows commits, messages, and committer
- [ ] SSH?
- [ ] Slackify in Tools module

_Copied from original issue: grabear/Orthologs-Project#26_

**Comment by sdhutchins** [comment]
I added `notify` to this, but I think it's going to remain an optional sort of class.

Also, isn't there a way to create a package and allow people to pip install with only certain modules?

**Comment by sdhutchins** [comment]
Doesn't seem relevant anymore.
