### ISSUE TITLE
Make a list of startup processes.  (host:port if applicable)

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#29]
_From @grabear on April 13, 2017 23:58_

- [X] Cockpit (162.243.56.106:9090)
- [x] Shiny Server (162.243.56.106:3838)
- [x] R-Studio Server (162.243.56.106:8787)
- [X] Flask (162.243.56.106:5252)
_________________________________________________________________________________________________________________

- [ ] - Wasabi (162.243.56.106:8000)

- [ ] - FTP
- [ ] - RichFilemanager

_Copied from original issue: grabear/Orthologs-Project#25_

**Comment by grabear** [comment]
Added Cockpit in order to monitor the server.  Digital Ocean's website also does some of this @sdhutchins

**Comment by sdhutchins** [comment]
Placing this on the backburner for now.
