### ISSUE TITLE
Integrate full pipeline

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#32]
***Things to remember for each step***
- [ ] Background scripts
    - [ ] Weekly or Monthly Updates for BLAST database (1 degree of archiving)
    - [ ] Weekly or Monthly Updates for GenBank database (1 degree of archiving)
    - [ ] Email updates for milestones, and errors
    - [ ] Logging
    - [ ] Master Python and BASH script
        - [x] Configuration script
- [ ] Create tutorials with Markdown
_________________________________________________________________________________________________
***Tying it all together***
- [x] 1:  Integrate BLAST and GenBank Gathering
- [x] 2:  Integrate  Multi-FASTA creation
- [x] 3:  Integrate Alignment
    - [x] Integrate Guidance2
    - [x] Integrate Pal2Nal
- [ ] 4:  Integrate Tree generation
    - [x] Integrate IQTree
- [ ] 5:  Integrate PAML analysis
- [ ] 6:  Integrate R w/ python (send files from each server - DataMana)
- [ ] 7:  Integrate data w/ rshiny app
    - [ ] ggtree integration

_Copied from original issue: grabear/Orthologs-Project#22_

**Comment by sdhutchins** [comment]
Important to https://github.com/datasnakes/Datasnakes-Scripts/projects/3#card-4278460

**Comment by grabear** [comment]
@datasnakes/snakes The pipeline works with the default YAML configurations, but needs further testing on the MCSR.

**Comment by sdhutchins** [comment]
#38 will incorporate this.
