### ISSUE TITLE
Find a pipeline workflow package and integrate it

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/OrthoEvolution#38]
## Top Tasks
- [ ] Create a simple test that integrates finished modules.
- [ ] Morph existing pipeline with `argparse` or `janis` to use on command line.
- [ ] Enhance existing pipeline for SGE usage & multiple processes/cluster without SGE

## General Workflow
- [x] 1:  Integrate BLAST and GenBank Gathering
- [x] 2:  Integrate  Multi-FASTA creation
- [x] 3:  Integrate Alignment
    - [x] Integrate Guidance2
    - [x] Integrate Pal2Nal
    - [x] Integrate clustalomega
- [ ] 4:  Integrate Tree generation
    - [x] Integrate IQTree
- [ ] 5:  Integrate PAML analysis
- [ ] 6:  Integrate R w/ python (send files from each server - DataMana)
- [ ] 7:  Integrate data w/ rshiny app
    - [ ] ggtree integration

**Comment by sdhutchins** [comment]
Could be best to use or load snakefiles with pkgresources.

```python
import pkg_resources
pkg_resources.resource_filename("myworkflow", "Snakefile")
```

**Comment by sdhutchins** [comment]
Additionally, per the conversation at https://bitbucket.org/snakemake/snakemake/issues/137/pipeline-installation-as-a-package...
Could be a good idea to create a wrapper for the snakefiles and make that part of the cli

`orthoevol --pipeline blast` would be calling the snakemake command (`snakemake --snakefile /path/to/snakefile` which wouldn't really be the path - we'd just be using pkgresources in the command).

Furthermore, that might make the `Pipeline` folder or module obsolete as we could just place those files in https://github.com/datasnakes/OrthoEvolution/tree/master/OrthoEvol/Manager/config.

Not sure yet. Let me know what you think @grabear

**Comment by grabear** [comment]
Will chime in on this later.  I will also just leave this here:  https://github.com/pditommaso/awesome-pipeline

Haven't really looked at that in a long time, but I'm going to parse it again just FWIW.  Snakemake seems pretty legit regardless.

**Comment by sdhutchins** [comment]
Everything pipeline related is like a notch harder...lol but I think snakemake can do what we want and it's just better designed for bioinformatics and python.

I'll give that list a look again. I haven't looked in a while myself. I'm going to test out a snakefile this weekend just with the blast stuff and see what that's like.

**Comment by grabear** [comment]
If we're going to use snakemake can I remove the Luigi stuff from the `Tools/SGE` module??

**Comment by sdhutchins** [comment]
https://github.com/datasnakes/OrthoEvolution/issues/148#issuecomment-499149314

**Comment by sdhutchins** [comment]
This issue will be addressed by https://github.com/datasnakes/orthoevol-snakemake
