### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#77]
As it stands, we are in a fairly stable place #36 #33 #66 and others have all given our project a well defined shape and functionality.

For me in particular, I need to add documentation to the Classes and modules that I've created.

- [x] Mini Tutorial
- [ ] Additions to main package README file
- [ ] Basic workflow vs Full workflow
- [x] Cookies (custom cookiecutter templates)
- [x] Manager module and Management class
- [ ] DataManagement class
- [ ] MultipleSequenceAlignment class
- [ ] GenBank class
- [ ] CompGenBLASTn
- [x] I'm definitely forgetting something.

**Comment by sdhutchins** [comment]
I was going for [this](https://github.com/datasnakes/Datasnakes-Scripts/blob/master/Datasnakes/README.md) to be our tutorial's location. 

I have a lot more to write for individual readme's as well.

**Comment by sdhutchins** [comment]
Will be addressed in #111
