### ISSUE TITLE
Combine data_management and the Luigi class

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#82]
##### What are you trying to accomplish?
The Pipeline module is great.  Whenever #38 is finished, the functionality in Manager/data_management.py needs to be used/moved in the Pipeline module.  

##### What is the issue?
The workflow is awkward as it stands.
Will help with #32.

**Comment by sdhutchins** [comment]
Yeah, I'm all for combining them.

**Comment by sdhutchins** [comment]
Luigi will likely be scrapped. Time to get back to the drawing board on pipeline creation.
