### ISSUE TITLE
Weird importing issue.

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#84]
https://github.com/datasnakes/Datasnakes-Scripts/commit/03c6514a9a4a035ff5c72c63bf2456b092368545#commitcomment-24706630

When using DataManagement, there was an Error when importing CompGenBLASTn.

**Comment by grabear** [comment]
Currently, our __init__.py files look like this:
```python
from .orthologs_blastn import OrthoBlastN
from .comparative_genetics_files import CompGenFiles
from .comparative_genetics_objects import CompGenObjects
from Datasnakes.Orthologs import OrthologsWarning
import warnings

# Make this explicit, then they show up in the API docs
__all__ = ("CompGenObjects",
           "CompGenFiles",
           "OrthoBlastN"
           )
...
```
While useful in shortening our code length, it can also cause issues with circular dependencies.

When trying to import Oven, you also import classes from .management, which inherently import the Oven class and therefore throws errors.

As a solution I might just remove the imports at the top, so it will look more like this:
```python
from Datasnakes.Orthologs import OrthologsWarning
import warnings

# Make this explicit, then they show up in the API docs
__all__ = ("CompGenObjects",
           "CompGenFiles",
           "OrthoBlastN"
           )
...
```

**Comment by sdhutchins** [comment]
@grabear any documentation on this or articles about doing this differently or better? I always thought the standard was using

```python
from .comparative_genetics_files import CompGenFiles`
``

but I don't know. Might check python's packaging docs.

**Comment by sdhutchins** [comment]
Might be case by case. Just took a look at Biopython's and they have it a number of ways. Not necessarily consistent.

**Comment by sdhutchins** [comment]
But wherever it is breaking or broken, does need to be fixed in whatever way needed. @grabear

**Comment by grabear** [comment]
Yea it will be on a per module basis.  I just used the Orthologs init.py because that's what I had open.  Manager and Cookies are interdependent, so they will need to be modulated.

**Comment by grabear** [comment]
This has been fixed.
