### ISSUE TITLE
Integrate LogIt into package

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#88]
* Use LogIt as a general logging tool.
    * Use in each module and make a master log.
    * Give each module a specific color.

**Comment by grabear** [comment]
Will address some aspects of https://github.com/datasnakes/Datasnakes-Scripts/issues/83

**Comment by sdhutchins** [comment]
I like the idea of slackify in the pipeline/datamanagement realm.

**Comment by grabear** [comment]
LogIt integration:
* Cookies
  - [ ] cookie_jar.py
* Manager
  - [ ]   management.py
  - [ ]   data_management.py

**Comment by sdhutchins** [comment]
Probably needs to be added to the FTP module.

**Comment by sdhutchins** [comment]
@grabear status here?

**Comment by grabear** [comment]
Slackify integration:
* Cookies
  - [ ] cookie_jar.py
* Manager
  - [ ]   management.py
  - [ ]   data_management.py
* Orthologs
  - [ ] msa.py
  - [ ] blastn_comparative_genetics.py
  - [ ] comparative_genetics_files.py
  - [ ] comparative_genetics_objects.py
  - [ ] genbank.py
* Pipeline
* Tools
  - [ ] ftp
  - [ ] sge
  - [ ] zipper
  - [ ] send2server

**Comment by sdhutchins** [comment]
do we want to integrate that automatically or just with the pipeline? @grabear

**Comment by grabear** [comment]
- [ ] Add a critical level.  Change the _error_ level color to dark red, and the _critical_ level color to bright red as it is [here](https://github.com/xolox/python-coloredlogs).

**Comment by sdhutchins** [comment]
There's a critical level. It's just red as well. @grabear

**Comment by sdhutchins** [comment]
@grabear There's no color for it for some odd reason. Might go to logzero and see if they'll add one. I also think they have an issue related to this.

**Comment by sdhutchins** [comment]
@grabear Check this issue https://github.com/metachris/logzero/issues/12

**Comment by sdhutchins** [comment]
@grabear adding critical level color now.

**Comment by sdhutchins** [comment]
![image](https://user-images.githubusercontent.com/20976111/35302240-64d7a6a8-0053-11e8-8723-854b3d8eec77.png)

Thoughts?

**Comment by sdhutchins** [comment]
For some reason I can't find the code that did this. hmm
