### ISSUE TITLE
Figure out Perl to Python tags.

### ISSUE THREAD

**Issue by grabear** [datasnakes/OrthoEvolution#92]
Manager/BioSQL is causing our code to be tagged with Perl instead of Python.

The only solution is to change the Perl scripts to python scripts.

**Comment by sdhutchins** [comment]
![Alt Text](https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif)

**Comment by grabear** [comment]
@sdhutchins Haha.  didn't know you could do gifs!

**Comment by sdhutchins** [comment]
@grabear Check out https://github.com/ctSkennerton/BioSQL-Extensions

**Comment by grabear** [comment]
https://github.com/datasnakes/Datasnakes-Scripts/commit/c862537742425beaceafeb6021cd7b16655235b5 This should resolve the problem,, once we've pushed to master.  

https://github.com/github/linguist

**Comment by sdhutchins** [comment]
:sunglasses:

**Comment by sdhutchins** [comment]
This was addressed in #120, right? @grabear

**Comment by grabear** [comment]
Hypothetically, but we won't know if it works for sure until we merge to master.

**Comment by sdhutchins** [comment]
Addressed when merged to master #128
